import type { Metadata } from 'next'
import 'react-toastify/dist/ReactToastify.css'
import '../globals.css'
import Providers from '../providers'
import { LeftSidebar } from '@/components/admin/leftNavbar'
import { Footer } from '@/components/admin/footer'
import { LeftSubSidebar } from '@/components/admin/leftSubNavbar'

export const metadata: Metadata = {
  title: 'My Gym',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="flex w-full">
            <LeftSidebar />
            <LeftSubSidebar />
            <div className="pt-4 w-full bg-gray-100 p-8">{children}</div>
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
