import type { Metadata } from 'next'
import 'react-toastify/dist/ReactToastify.css'
import '../globals.css'
import Providers from '../providers'
import { Footer } from '@/components/authenticated/footer'
import Navigation from './navigation'

export const metadata: Metadata = {
  title: 'My Gym - Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="flex w-full">
            <Navigation />
            <div className="pt-4 w-full bg-gray-100 p-8">{children}</div>
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
